name: CI

on: 
  push:
    branches:
      - master

jobs:
  latex:
    runs-on: ubuntu-latest
    steps:
    - name: LaTeX-to-PDF github action
      uses: forkbabu/AutoEdit@2957aee6d07356b3ce2db56cb4829eee15bceb1b
