name: CI

on: 
  push:
    branches:
      - master

jobs:
  latex:
    runs-on: ubuntu-latest
    steps:
    - name: Uberblatt
      uses: ottojo/uberblatt-action@5c0a0ee8cf7f367a8739ebce170b5b7387f28f34
