name: Build LaTeX and deploy on GH Releases
on:
  push:

jobs:
  Build-LaTeX:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch tags
        shell: bash
        run: git fetch --tags -f
      - name: Install TeXLive
        uses: DanySK/setup-texlive-action@master
      - name: Compile LaTeX
        uses: DanySK/compile-latex-action@master
      - name: Autotag
        uses: DanySK/semver-autotag-action@master
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      name: Build LaTeX and deploy on GH Releases
on:
  push:

jobs:
  Build-LaTeX:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch tags
        shell: bash
        run: git fetch --tags -f
      - name: Install TeXLive
        uses: DanySK/setup-texlive-action@master
      - name: Compile LaTeX
        uses: DanySK/compile-latex-action@master
      - name: Autotag
        uses: DanySK/semver-autotag-action@master
      - name: Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG=$(git describe --tags --exact-match HEAD)
          hub release create -m "$(git tag -l --format='%(contents)' "$TAG")" "$TAG" || true
          while IFS= read -r file; do
            pdf="${file%.*}.pdf"
            echo "Delivering file $pdf"
            hub release edit -m '' -a "$pdf" "$TAG"
          done <"success-list"

