# This is a basic workflow to help you get started with Actions

name: PDF generate and store
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Latex-multicompiler
        uses: Jatus93/Latex-multicompiler@97081e71ec28ea353c04532b73baa1217d1e38f6
        with:
          path_to_list: notes/
      
